### ISSUE TITLE
unable to import yamlcalc

### ISSUE THREAD

**Issue by iamihgam** [zilogic-systems/yamlcalc#1]
@bravegnu 
I  am trying to import the yamlcalc to work with . I could successfully clone it from github. When i try to pip install , the follow error occurs. 
"Collecting yamlcalc
  Could not find a version that satisfies the requirement yamlcalc (from versions: )
No matching distribution found for yamlcalc"
- I have updated the pip install to recent version
- tried out in both py 2.7x and py 3.4x versions. both show the same result

**Comment by bravegnu** [comment]
If you are within the yamlcalc folder then you should do

```
$ pip install --user .
```

**Comment by iamihgam** [comment]
Nope, the issue is not resolved . 
within the yamlcalc folder it  shows 
`You must give at least one requirement to install (see "pip help install")`
this time i have used my xubuntu at my office. 
anyhow i could resolve this during coming meeting at DUTA

**Comment by bravegnu** [comment]
I guess you missed the "dot" / "period" / "current-directory" in the command.

**Comment by iamihgam** [comment]
Yes, the dot follows a space after "--user"

thanks. resolved
